/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author ASUS
 */
public class FrmGestionActivos extends javax.swing.JFrame {

    private Modelo.Persona usuarioActual;
    private Controlador.ControladorHardware controladorHW;
    private Controlador.ControladorSoftware controladorSW;
    private Controlador.ActivoDAO activoDAO;

    /**
     * Creates new form FrmGestionActivos
     */
    public FrmGestionActivos(Modelo.Persona usuario) {
        this.usuarioActual = usuario;
        initComponents(); // Obligatorio: Carga los botones y cajas de texto
        inicializarSistema();
    }

    private void inicializarSistema() {
        try {
            java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:lab_inventario.db");
            this.activoDAO = new Controlador.ActivoDAO(conn);

            Controlador.Servicios.ServicioAutorizacion auth = new Controlador.Servicios.ServicioAutorizacion();
            Controlador.Servicios.ServicioHardware servHW = new Controlador.Servicios.ServicioHardware();
            Controlador.Servicios.ServicioSoftware servSW = new Controlador.Servicios.ServicioSoftware();

            this.controladorHW = new Controlador.ControladorHardware(auth, servHW, activoDAO);
            this.controladorSW = new Controlador.ControladorSoftware(auth, servSW, activoDAO);

            cargarTablaActivos();
            aplicarPermisosPorRol();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error base de datos: " + e.getMessage());
        }
    }

    private void cargarTablaActivos() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblActivos.getModel();
        model.setRowCount(0);

        java.util.List<Modelo.Hardware> listaHW = controladorHW.obtenerHardwareVisible(usuarioActual);
        for (Modelo.Hardware hw : listaHW) {
            model.addRow(new Object[]{hw.getCodigo(), hw.getNombre(), hw.getTipoActivo(), hw.getEstado()});
        }

        java.util.List<Modelo.Software> listaSW = controladorSW.obtenerSoftwareVisible(usuarioActual);
        for (Modelo.Software sw : listaSW) {
            model.addRow(new Object[]{sw.getCodigo(), sw.getNombre(), sw.getTipoActivo(), sw.getEstado()});
        }
    }

    private void aplicarPermisosPorRol() {
        if (usuarioActual.getNivelAcceso() == Modelo.NivelAcceso.USUARIO) {
            btnGuardar.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnLimpiar.setEnabled(false);
        }
    }

    private void limpiarFormulario() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtCosto.setText("");
        txtFechaAdq.setText("");
        txtFrecuenciaMant.setText("");
        txtNumEquipos.setText("");
        txtFechaRenovacion.setText("");
        txtCodigo.setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblActivos = new javax.swing.JTable();
        txtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbTipoActivo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFechaAdq = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFrecuenciaMant = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumEquipos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFechaRenovacion = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Tipo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblActivos);

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        cmbTipoActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HARDWARE", "SOFTWARE", "LICENCIA", "SUBSCRIPCION" }));

        jLabel2.setText("Tipo Activo:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Descripción:");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        jLabel5.setText("Costo Adquisición:");

        jLabel6.setText("Fecha Adquisición (AAAA-MM-DD):");

        jLabel7.setText("Frecuencia Mantenimiento (meses):");

        txtFrecuenciaMant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFrecuenciaMantActionPerformed(evt);
            }
        });

        jLabel8.setText("Número Equipos:");

        jLabel9.setText("Fecha Renovación (AAAA-MM-DD):");

        btnLimpiar.setText("Nuevo / Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar Activo");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver al Menú");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(txtFechaAdq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTipoActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFrecuenciaMant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaRenovacion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnVolver)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtFechaAdq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFrecuenciaMant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtNumEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtFechaRenovacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnVolver))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtFrecuenciaMantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFrecuenciaMantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFrecuenciaMantActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        try {
            if (txtCodigo.getText().trim().isEmpty() || txtNombre.getText().trim().isEmpty() || txtCosto.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Complete los campos obligatorios.");
                return;
            }

            String codigo = txtCodigo.getText().trim();
            String nombre = txtNombre.getText().trim();
            String desc = txtDescripcion.getText().trim();
            double costo = Double.parseDouble(txtCosto.getText().trim());
            java.time.LocalDate fechaAdq = java.time.LocalDate.parse(txtFechaAdq.getText().trim());
            String tipo = cmbTipoActivo.getSelectedItem().toString();

            if ("HARDWARE".equals(tipo)) {
                int freq = Integer.parseInt(txtFrecuenciaMant.getText().trim());
                Modelo.Hardware hw = new Modelo.Hardware(codigo, nombre, desc, costo, fechaAdq, freq);
                activoDAO.crear(hw, "LAB-DEFAULT", usuarioActual.getCodigo());
            } else {
                double numEq = Double.parseDouble(txtNumEquipos.getText().trim());
                java.time.LocalDate fechaRen = java.time.LocalDate.parse(txtFechaRenovacion.getText().trim());
                Modelo.Software sw;

                if ("SUBSCRIPCION".equals(tipo)) {
                    sw = new Modelo.Subscripcion("ANUAL", numEq, fechaRen, codigo, nombre, desc, costo, fechaAdq);
                } else if ("LICENCIA".equals(tipo)) {
                    sw = new Modelo.Licencia("LIC-" + codigo, numEq, fechaRen, codigo, nombre, desc, costo, fechaAdq);
                } else {
                    sw = new Modelo.Software(numEq, fechaRen, codigo, nombre, desc, costo, fechaAdq);
                }
                activoDAO.crear(sw, "LAB-DEFAULT", usuarioActual.getCodigo());
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Activo guardado exitosamente.");
            limpiarFormulario();
            cargarTablaActivos();

        } catch (java.time.format.DateTimeParseException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Use AAAA-MM-DD.");
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese valores numéricos validos en Costo, Frecuencia o Equipos.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tblActivos.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un activo de la tabla para eliminar.");
            return;
        }

        String codigo = tblActivos.getValueAt(fila, 0).toString();
        String tipo = tblActivos.getValueAt(fila, 2).toString();

        int resp = javax.swing.JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar el activo " + codigo + "?");
        if (resp == javax.swing.JOptionPane.YES_OPTION) {
            if ("HARDWARE".equals(tipo)) {
                String res = controladorHW.eliminarActivo(usuarioActual, codigo);
                javax.swing.JOptionPane.showMessageDialog(this, res);
            } else {
                activoDAO.eliminar(codigo);
                javax.swing.JOptionPane.showMessageDialog(this, "Activo eliminado.");
            }
            cargarTablaActivos();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        new FrmMenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbTipoActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblActivos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFechaAdq;
    private javax.swing.JTextField txtFechaRenovacion;
    private javax.swing.JTextField txtFrecuenciaMant;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumEquipos;
    // End of variables declaration//GEN-END:variables
}
